file_system_types:
  cip:
    url: 'https://storage.kernelci.org/images/rootfs/cip/20220728'
    arch_map:
      amd64: [{arch: x86_64}]

file_systems:
  cip_nfs:
    type: cip
    ramdisk: 'qemu-{arch}/cip-core-image-kernelci-cip-core-buster-qemu-{arch}-initrd.img.gz'
    nfs: 'qemu-{arch}/cip-core-image-kernelci-cip-core-buster-qemu-{arch}.tar.gz'
    root_type: nfs

test_plans:
  baseline-cip-nfs:
    rootfs: cip_nfs
    pattern: 'baseline/{category}-{method}-{protocol}-nfs-baseline-template.jinja2'
    params:
      priority: 85
    filters:
      - passlist: {'tree': ['cip']}

